# Lackluster theme for Yazi

[mgr]
border_style = { fg = "#444444" }
cwd = { fg = "#7788aa" }
hovered = { bg = "#2a2a2a", fg = "#deeeed", bold = true }
preview_hovered = { bg = "#191919", fg = "#deeeed", bold = true }
find_keyword = { fg = "#789978", bold = true }
find_position = { fg = "#444444" }
marker_selected = { bg = "#2a2a2a", fg = "#708090" }
marker_copied = { bg = "#789978", fg = "#789978" }
marker_cut = { bg = "#d70000", fg = "#d70000" }
tab_active = { bg = "#708090", fg = "#101010" }
tab_inactive = { bg = "#191919", fg = "#444444" }

count_selected = { bg = "#708090", fg = "#101010" }
count_copied = { bg = "#789978", fg = "#101010" }
count_cut = { bg = "#d70000", fg = "#101010" }

[status]
separator_open = ""
separator_close = ""
mode_normal = { bg = "#708090", fg = "#101010", bold = true }
mode_select = { bg = "#789978", fg = "#101010", bold = true }
mode_unset = { bg = "#d70000", fg = "#101010", bold = true }
permissions_r = { fg = "#abab77" }
permissions_w = { fg = "#d70000" }
permissions_x = { fg = "#789978" }
permissions_s = { fg = "#444444" }
permissions_t = { fg = "#708090" }
progress_label = { fg = "#deeeed" }
progress_normal = { fg = "#708090" }
progress_error = { fg = "#d70000" }

[completion]
active = { bg = "#2a2a2a", fg = "#708090" }
inactive = { fg = "#444444" }
border = { fg = "#444444" }

[input]
border = { fg = "#444444" }
title = { fg = "#deeeed" }
value = { fg = "#deeeed" }
selected = { bg = "#2a2a2a" }

[select]
active = { fg = "#708090" }
inactive = { fg = "#444444" }
border = { fg = "#444444" }

[help]
on = { fg = "#708090" }
run = { fg = "#7788aa" }
desc = { fg = "#444444" }
hovered = { bg = "#2a2a2a", fg = "#deeeed" }
footer = { fg = "#444444" }

[filetype]
rules = [
  { mime = "image/*", fg = "#7788aa" },
  { mime = "video/*", fg = "#abab77" },
  { mime = "audio/*", fg = "#abab77" },
  { mime = "application/zip", fg = "#708090" },
  { mime = "application/gzip", fg = "#708090" },
  { mime = "application/x-tar", fg = "#708090" },
  { mime = "application/x-bzip", fg = "#708090" },
  { mime = "application/x-bzip2", fg = "#708090" },
  { mime = "application/x-7z-compressed", fg = "#708090" },
  { mime = "application/x-rar", fg = "#708090" },
  { mime = "application/pdf", fg = "#d70000" },
  { mime = "inode/directory", fg = "#7788aa", bold = true },
  { mime = "*", fg = "#deeeed" }
]

[tasks]
border = { fg = "#444444" }
title = { fg = "#deeeed" }
hovered = { bg = "#2a2a2a", fg = "#deeeed" }

[which]
mask = { bg = "#101010" }
cand = { fg = "#7788aa" }
rest = { fg = "#444444" }
desc = { fg = "#444444" }
separator_style = { fg = "#444444" }
