# josean color theme for Yazi
[manager]
border_style = { fg = "#547998" }
cwd = { fg = "#2CF9ED" }
hovered = { bg = "#143652", fg = "#CBE0F0", bold = true }
preview_hovered = { bg = "#011423", fg = "#CBE0F0", bold = true }
find_keyword = { fg = "#44FFB1", bold = true }
find_position = { fg = "#627E97" }
marker_selected = { bg = "#143652", fg = "#B388FF" }
marker_copied = { bg = "#44FFB1", fg = "#44FFB1" }
marker_cut = { bg = "#E52E2E", fg = "#E52E2E" }
tab_active = { bg = "#0FC5ED", fg = "#011423" }
tab_inactive = { bg = "#011423", fg = "#627E97" }

count_selected = { bg = "#B388FF", fg = "#011423" }
count_copied = { bg = "#44FFB1", fg = "#011423" }
count_cut = { bg = "#E52E2E", fg = "#011423" }

[status]
separator_open = ""
separator_close = ""
mode_normal = { bg = "#0FC5ED", fg = "#011423", bold = true }
mode_select = { bg = "#44FFB1", fg = "#011423", bold = true }
mode_unset = { bg = "#E52E2E", fg = "#011423", bold = true }
permissions_r = { fg = "#FFE073" }
permissions_w = { fg = "#E52E2E" }
permissions_x = { fg = "#44FFB1" }
permissions_s = { fg = "#627E97" }
permissions_t = { fg = "#0FC5ED" }
progress_label = { fg = "#CBE0F0" }
progress_normal = { fg = "#0FC5ED" }
progress_error = { fg = "#E52E2E" }

[completion]
active = { bg = "#143652", fg = "#B388FF" }
inactive = { fg = "#627E97" }
border = { fg = "#547998" }

[input]
border = { fg = "#547998" }
title = { fg = "#CBE0F0" }
value = { fg = "#CBE0F0" }
selected = { bg = "#143652" }

[select]
active = { fg = "#B388FF" }
inactive = { fg = "#627E97" }
border = { fg = "#547998" }

[help]
on = { fg = "#B388FF" }
run = { fg = "#2CF9ED" }
desc = { fg = "#627E97" }
hovered = { bg = "#143652", fg = "#CBE0F0" }
footer = { fg = "#627E97" }

[filetype]
rules = [
  { mime = "image/*", fg = "#2CF9ED" },
  { mime = "video/*", fg = "#FFE073" },
  { mime = "audio/*", fg = "#FFE073" },
  { mime = "application/zip", fg = "#B388FF" },
  { mime = "application/gzip", fg = "#B388FF" },
  { mime = "application/x-tar", fg = "#B388FF" },
  { mime = "application/x-bzip", fg = "#B388FF" },
  { mime = "application/x-bzip2", fg = "#B388FF" },
  { mime = "application/x-7z-compressed", fg = "#B388FF" },
  { mime = "application/x-rar", fg = "#B388FF" },
  { mime = "application/pdf", fg = "#E52E2E" },
  { mime = "inode/directory", fg = "#0FC5ED", bold = true },
  { mime = "*", fg = "#CBE0F0" }
]

[tasks]
border = { fg = "#547998" }
title = { fg = "#CBE0F0" }
hovered = { bg = "#143652", fg = "#CBE0F0" }

[which]
mask = { bg = "#011628" }
cand = { fg = "#2CF9ED" }
rest = { fg = "#627E97" }
desc = { fg = "#627E97" }
separator_style = { fg = "#547998" }
