# Kanagawa colors for Yazi
[mgr]
cwd = { fg = "#7E9CD8" }

[status]
separator_open = ""
separator_close = ""

[filetype]
rules = [
  { mime = "image/*", fg = "#98BB6C" },
  { mime = "video/*", fg = "#957FB8" },
  { mime = "audio/*", fg = "#7FB4CA" },
  { mime = "application/zip", fg = "#FF5D62" },
  { mime = "application/gzip", fg = "#FF5D62" },
  { mime = "application/x-tar", fg = "#FF5D62" },
  { mime = "application/x-bzip", fg = "#FF5D62" },
  { mime = "application/x-7z-compressed", fg = "#FF5D62" },
  { mime = "application/x-rar", fg = "#FF5D62" },
]
