# Carbonfox theme for Yazi

[mgr]
border_style = { fg = "#525253" }
cwd = { fg = "#33B1FF" }
hovered = { bg = "#2a2a2a", fg = "#f2f4f8", bold = true }
preview_hovered = { bg = "#0c0c0c", fg = "#f2f4f8", bold = true }
find_keyword = { fg = "#25be6a", bold = true }
find_position = { fg = "#525253" }
marker_selected = { bg = "#2a2a2a", fg = "#BE95FF" }
marker_copied = { bg = "#25be6a", fg = "#25be6a" }
marker_cut = { bg = "#EE5396", fg = "#EE5396" }
tab_active = { bg = "#78A9FF", fg = "#161616" }
tab_inactive = { bg = "#0c0c0c", fg = "#525253" }

count_selected = { bg = "#BE95FF", fg = "#161616" }
count_copied = { bg = "#25be6a", fg = "#161616" }
count_cut = { bg = "#EE5396", fg = "#161616" }

[status]
separator_open = ""
separator_close = ""
mode_normal = { bg = "#78A9FF", fg = "#161616", bold = true }
mode_select = { bg = "#25be6a", fg = "#161616", bold = true }
mode_unset = { bg = "#EE5396", fg = "#161616", bold = true }
permissions_r = { fg = "#3DDBD9" }
permissions_w = { fg = "#EE5396" }
permissions_x = { fg = "#25be6a" }
permissions_s = { fg = "#525253" }
permissions_t = { fg = "#78A9FF" }
progress_label = { fg = "#f2f4f8" }
progress_normal = { fg = "#78A9FF" }
progress_error = { fg = "#EE5396" }

[completion]
active = { bg = "#2a2a2a", fg = "#BE95FF" }
inactive = { fg = "#525253" }
border = { fg = "#525253" }

[input]
border = { fg = "#525253" }
title = { fg = "#f2f4f8" }
value = { fg = "#f2f4f8" }
selected = { bg = "#2a2a2a" }

[select]
active = { fg = "#BE95FF" }
inactive = { fg = "#525253" }
border = { fg = "#525253" }

[help]
on = { fg = "#BE95FF" }
run = { fg = "#33B1FF" }
desc = { fg = "#525253" }
hovered = { bg = "#2a2a2a", fg = "#f2f4f8" }
footer = { fg = "#525253" }

[filetype]
rules = [
  { mime = "image/*", fg = "#33B1FF" },
  { mime = "video/*", fg = "#3DDBD9" },
  { mime = "audio/*", fg = "#3DDBD9" },
  { mime = "application/zip", fg = "#BE95FF" },
  { mime = "application/gzip", fg = "#BE95FF" },
  { mime = "application/x-tar", fg = "#BE95FF" },
  { mime = "application/x-bzip", fg = "#BE95FF" },
  { mime = "application/x-bzip2", fg = "#BE95FF" },
  { mime = "application/x-7z-compressed", fg = "#BE95FF" },
  { mime = "application/x-rar", fg = "#BE95FF" },
  { mime = "application/pdf", fg = "#EE5396" },
  { mime = "inode/directory", fg = "#78A9FF", bold = true },
  { mime = "*", fg = "#f2f4f8" }
]

[tasks]
border = { fg = "#525253" }
title = { fg = "#f2f4f8" }
hovered = { bg = "#2a2a2a", fg = "#f2f4f8" }

[which]
mask = { bg = "#161616" }
cand = { fg = "#33B1FF" }
rest = { fg = "#525253" }
desc = { fg = "#525253" }
separator_style = { fg = "#525253" }
