# Lackluster theme for Helix
# Based on slugbyte/lackluster.nvim (hack variant)

attribute = { fg = "lack" }
comment = { fg = "comment" }
"comment.block.documentation" = { fg = "yellow" }
"comment.line.documentation" = { fg = "yellow" }
constant = { fg = "orange" }
"constant.builtin" = { fg = "blue" }
"constant.character" = { fg = "green" }
"constant.character.escape" = { fg = "lack" }
constructor = { fg = "blue" }
function = { fg = "luster" }
"function.builtin" = { fg = "blue" }
"function.macro" = { fg = "lack" }
"function.special" = { fg = "lack" }
keyword = { fg = "gray6" }
"keyword.control" = { fg = "gray6" }
"keyword.control.import" = { fg = "lack" }
"keyword.control.return" = { fg = "green" }
"keyword.directive" = { fg = "lack" }
"keyword.function" = { fg = "gray6" }
"keyword.operator" = { fg = "gray6" }
label = { fg = "blue" }
namespace = { fg = "lack" }
operator = { fg = "gray7" }
punctuation = { fg = "gray7" }
special = { fg = "blue" }
string = { fg = "gray7" }
"string.regexp" = { fg = "orange" }
"string.special" = { fg = "blue" }
tag = { fg = "lack" }
type = { fg = "luster" }
"type.builtin" = { fg = "luster" }
"type.enum.variant" = { fg = "orange" }
variable = { fg = "luster" }
"variable.builtin" = { fg = "red" }
"variable.other.member" = { fg = "luster" }
"variable.parameter" = { fg = "gray8" }

"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "menu-bg", fg = "luster" }
"markup.heading.hover" = { bg = "selection" }
"markup.italic" = { }
"markup.link" = { fg = "blue", underline = { style = "line" } }
"markup.link.label" = { fg = "lack" }
"markup.link.text" = { fg = "lack" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "orange", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "comment" }
"markup.normal.hover" = { fg = "gray6" }
"markup.raw" = { fg = "lack" }
"markup.raw.inline" = { bg = "black", fg = "blue" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diff.delta" = { fg = "blue" }
"diff.delta.moved" = { fg = "blue" }
"diff.minus" = { fg = "red" }
"diff.plus" = { fg = "green" }

error = { fg = "red" }
warning = { fg = "yellow" }
info = { fg = "blue" }
hint = { fg = "lack" }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"diagnostic.warning" = { underline = { style = "curl", color = "yellow"} }
"diagnostic.info" = { underline = { style = "curl", color = "blue"} }
"diagnostic.hint" = { underline = { style = "curl", color = "lack" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"ui.background" = { bg = "bg", fg = "luster" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "orange", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "menu-bg" }
"ui.help" = { bg = "menu-bg", fg = "luster" }
"ui.linenr" = { fg = "gray4" }
"ui.linenr.selected" = { fg = "gray6" }
"ui.menu" = { bg = "menu-bg", fg = "luster" }
"ui.menu.selected" = { bg = "selection" }
"ui.popup" = { bg = "menu-bg", fg = "gray6" }
"ui.selection" = { bg = "selection" }
"ui.selection.primary" = { bg = "selection" }
"ui.statusline" = { bg = "statusline", fg = "gray6" }
"ui.statusline.inactive" = { bg = "menu-bg", fg = "gray4" }
"ui.statusline.normal" = { bg = "lack", fg = "bg", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "green", fg = "bg", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "blue", fg = "bg", modifiers = ["bold"] }
"ui.text" = { fg = "luster" }
"ui.text.focus" = { bg = "selection" }
"ui.text.inactive" = { fg = "comment" }
"ui.text.info" = { bg = "menu-bg", fg = "luster" }
"ui.text.directory" = { fg = "lack" }
"ui.virtual.ruler" = { bg = "gray4" }
"ui.virtual.whitespace" = { fg = "gray3" }
"ui.virtual.inlay-hint" = { bg = "gray1", fg = "gray5" }
"ui.virtual.jump-label" = { fg = "orange", modifiers = ["bold"] }
"ui.window" = { fg = "gray1", modifiers = ["bold"] }

[palette]
red = "#d70000"
orange = "#ffaa88"
yellow = "#abab77"
green = "#789978"
blue = "#7788aa"
lack = "#708090"
luster = "#deeeed"
comment = "#555555"
black = "#000000"
gray1 = "#080808"
gray2 = "#191919"
gray3 = "#2a2a2a"
gray4 = "#444444"
gray5 = "#555555"
gray6 = "#7a7a7a"
gray7 = "#aaaaaa"
gray8 = "#cccccc"
gray9 = "#dddddd"

bg = "#101010"
menu-bg = "#191919"
popup-bg = "#1a1a1a"
statusline = "#242424"
selection = "#2a2a2a"
